### ISSUE TITLE
Sync finds contacts but not saving to address book

### ISSUE THREAD

**Issue by stuartdwilliams** [stwa/google-addressbook#15]
I manually installed on cPanel. Went to address book and synced and after processing it said it found 300 or so contacts but none of them have saved, the DB is still empty.

I set up a cron job but it returned "Not on the "shell" (php-cli)"

Any advice please?

**Comment by guruhost** [comment]
I've got the same problem on a plain server with no Cpanel etc. Anyone with a suggestion/solution?

**Comment by stwa** [comment]
@stuartdwilliams 
Look at https://github.com/roundcube/roundcubemail/blob/master/program/include/clisetup.php, there is a check to identify if PHP is running from command line. I don't know anything about cPanel, so I can't help you with that.

@guruhost 
Can you find anything suspicious inside the logfiles? Is there any chance you have problems with your database setup?

**Comment by guruhost** [comment]
Hi stwa, it seems it is missing the mysql table. I thought that this is happening automatically due the installer. Issue solved by creating the table into the roundcube DB. I believe the other user with cpanel installed is missing the same.

Thanks

**Comment by stwa** [comment]
Great, thanks for your feedback!
