### ISSUE TITLE
Google Entries with multiple values for the same field.

### ISSUE THREAD

**Issue by bigmalletman** [stwa/google-addressbook#20]
Example:
My google contact is as follows:
Name: Daniel Wells
Home: daniel@personalwebsite.com
Work: daniel@happyworkcompany.com
Other: coolbook@kindle.com
Other: neatthing@cheese.com
Home: otheremail@gmail.com
Home: anotheremail@somewhereelse.com

The synced information that gets to RoundCube is:
Home: daniel@personalwebsite.com
Work: daniel@happyworkcompany.com
Other: coolbook@kindle.com

If there are multiple email accounts with the same type of email address, RoundCube will only add one for each. The same is true for the different types of phone numbers, etc.

**Comment by wolfgangkarall** [comment]
https://gist.github.com/wolfgangkarall/f0eadb81383895089825 works for me.

**Comment by bigmalletman** [comment]
The change above fixes my issue as well. Thanks.

**Comment by kd35a** [comment]
@wolfgangkarall Would you mind creating a pull request for this that @stwa could pull in?

**Comment by wolfgangkarall** [comment]
Ok, done.

**Comment by stwa** [comment]
I merged the pull request, thank you so much to everyone!
